---
title: "\"Finally\" kann nicht außerhalb einer Try-Anweisung verwendet werden."
ms.date: 07/20/2015
f1_keywords:
- vbc30382
- bc30382
helpviewer_keywords:
- BC30382
ms.assetid: 0314d8d2-18bc-4bbd-858c-0a18408b52fd
ms.openlocfilehash: 210f4cc25ba47d89839c65dc91042d884635d5db
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 03/15/2019
ms.locfileid: "58028887"
---
# <a name="finally-cannot-appear-outside-a-try-statement"></a>"Finally" kann nicht außerhalb einer Try-Anweisung verwendet werden.
`Finally` wird zum Beenden eines `Try...Catch...Finally` -Blocks verwendet, kann daher nur einmal am Ende des Blocks angegeben werden. Entweder ist `Finally`unnötig, oder die `Finally` -Anweisung befindet sich außerhalb des entsprechenden `Try` -Blocks.  
  
 **Fehler-ID:** BC30382  
  
## <a name="to-correct-this-error"></a>So beheben Sie diesen Fehler  
  
1.  Suchen und entfernen Sie die unnötige `Finally` -Anweisung.  
  
2.  Verschieben Sie die `Finally` -Anweisung an die gewünschte Position im Code.  
  
## <a name="see-also"></a>Siehe auch

- [Try...Catch...Finally-Anweisung](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
